import { sendSlackMessage } from "./util";

type ServerlessFnProps = {
  rossum_authorization_token: string;
  base_url: string;
  hook: string;
  settings: Record<string, unknown>;
  secrets: Record<string, unknown>;
};

export const rossum_hook_request_handler = async ({
  settings,
  secrets
}: ServerlessFnProps) => {
  console.log("🚀 Slack Notifier 🚀");
  const sendMessage = async (message) => {
    await sendSlackMessage(secrets.token, message, settings.channel_id);
  };
  sendMessage("This is generated by Notifier Test App");
};
