import { sendSlackMessage } from "./util";

type ServerlessFnProps = {
  settings: Record<string, unknown>;
  secrets: Record<string, unknown>;
  configure: boolean;
  payload: Record<string, unknown>;
};

export const rossum_hook_request_handler = async ({
  settings,
  secrets,
  payload,
  configure,
}: ServerlessFnProps) => {
  if (configure === true) {
    return {
      intent: {
        form: {
          schema: {
            type: "object",
            properties: {
              message: {
                type: "string",
              }
            },
          },
        },
      },
    };
  } else {
    const sendMessage = async (message) => {
      await sendSlackMessage(secrets.token, message, settings.channel_id);
    };
    sendMessage("This is generated by Notifier Test App");
    return {
      messages: [{ type: "info", content: payload.message }],
    };
  }
};
