name: Tag - Download report
on:
  push:
    branches:
      - main
    paths:
      - dist/download_report/**
jobs:
  call-reusable:
    uses: ./.github/workflows/_tag_release.yml
    with:
      tag_prefix: "ext/download_report/v"
