name: Tag - Kitten
on:
  push:
    branches:
      - main
    paths:
      - dist/kitten/**
jobs:
  call-reusable:
    uses: ./.github/workflows/_tag_release.yml
    with:
      tag_prefix: "ext/kitten/v"
