name: Tag - Lookup AI
on:
  push:
    branches:
      - main
    paths:
      - dist/lookup_ai/**
jobs:
  call-reusable:
    uses: ./.github/workflows/_tag_release.yml
    with:
      tag_prefix: "ext/lookup_ai/v"
