name: Tag - Lookup MDH
on:
  push:
    branches:
      - main
    paths:
      - dist/lookup_mdh/**
jobs:
  call-reusable:
    uses: ./.github/workflows/_tag_release.yml
    with:
      tag_prefix: "ext/lookup_mdh/v"
