name: Tag - Lookup MDH Python
on:
  push:
    branches:
      - main
    paths:
      - dist/lookup_mdh_py/**
jobs:
  call-reusable:
    uses: ./.github/workflows/_tag_release.yml
    with:
      tag_prefix: "ext/lookup_mdh_py/v"
