name: Tag - Lookup annotations
on:
  push:
    branches:
      - main
    paths:
      - dist/lookup_annotations/**
jobs:
  call-reusable:
    uses: ./.github/workflows/_tag_release.yml
    with:
      tag_prefix: "ext/lookup_annotations/v"
