name: Tag - Mini store
on:
  push:
    branches:
      - main
    paths:
      - dist/mini_store/**
jobs:
  call-reusable:
    uses: ./.github/workflows/_tag_release.yml
    with:
      tag_prefix: "ext/mini_store/v"
