name: Tag - Show schema IDs
on:
  push:
    branches:
      - main
    paths:
      - dist/list_schema_ids/**
jobs:
  call-reusable:
    uses: ./.github/workflows/_tag_release.yml
    with:
      tag_prefix: "ext/list_schema_ids/v"
