name: Tag - Slack message
on:
  push:
    branches:
      - main
    paths:
      - dist/slack_message/**
jobs:
  call-reusable:
    uses: ./.github/workflows/_tag_release.yml
    with:
      tag_prefix: "ext/slack_message/v"
